services:
  dartsstatistics:
    image: dartsstatistics
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9999:9000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tRyP6po*fc2sA$
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 6s
      retries: 10
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9995:80
    depends_on:
      - db